import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import projectsRouter from "./projects.js";
import analysisRouter from "./analysis.js";
import competitorsRouter from "./competitors.js";
import contentRouter from "./content.js";
import videosRouter from "./videos.js";
import renderRouter from "./render.js";
import imagesRouter from "./images.js";
import campaignsRouter from "./campaigns.js";
import authRouter from "./auth.js";
import onboardingRouter from "./onboarding.js";
import trialRouter from "./trial.js";
import adminRouter from "./admin.js";
import adminCreditsRouter from "./admin-credits.js";
import adminCreditStatusRouter from "./admin-credit-status.js";
import storageRouter from "./storage.js";
import googleAdsRouter from "./google-ads.js";
import metaAdsRouter from "./meta-ads.js";
import authMetaRouter from "./auth-meta.js";
import stripeRouter from "./stripe.js";
import seoRouter from "./seo.js";
import teamRouter from "./team.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(onboardingRouter);
router.use(trialRouter);
router.use(projectsRouter);
router.use(analysisRouter);
router.use(competitorsRouter);
router.use(contentRouter);
router.use(videosRouter);
router.use(renderRouter);
router.use(imagesRouter);
router.use(campaignsRouter);
router.use(adminRouter);
router.use(adminCreditsRouter);
router.use(adminCreditStatusRouter);
router.use(storageRouter);
router.use(googleAdsRouter);
router.use(metaAdsRouter);
router.use(authMetaRouter);
router.use(stripeRouter);
router.use(seoRouter);
router.use(teamRouter);

export default router;
