import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import projectsRouter from "./projects.js";
import analysisRouter from "./analysis.js";
import competitorsRouter from "./competitors.js";
import contentRouter from "./content.js";
import videosRouter from "./videos.js";
import renderRouter from "./render.js";
import imagesRouter from "./images.js";
import campaignsRouter from "./campaigns.js";
import authRouter from "./auth.js";
import onboardingRouter from "./onboarding.js";
import trialRouter from "./trial.js";
import adminRouter from "./admin.js";
import adminCreditsRouter from "./admin-credits.js";
import adminCreditStatusRouter from "./admin-credit-status.js";
import storageRouter from "./storage.js";
import googleAdsRouter from "./google-ads.js";
import metaAdsRouter from "./meta-ads.js";
import authMetaRouter from "./auth-meta.js";
import stripeRouter from "./stripe.js";
import seoRouter from "./seo.js";
import seoToolsRouter from "./seo-tools.js";
import teamRouter from "./team.js";
import usageRouter from "./usage.js";
import scenesRouter from "./scenes.js";
import assembleRouter from "./assemble.js";
import narrationRouter from "./narration.js";
import renderAdminRouter from "./renderAdmin.js";
import videoWalletRouter from "./video-wallet.js";
import adminVideoRouter from "./admin-video.js";
import analyzeWebsiteRouter from "./analyze-website.js";
import ownerRouter from "./owner.js";
import supportRouter from "./support.js";
import zTutorRouter from "./z-tutor.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(onboardingRouter);
router.use(trialRouter);
router.use(projectsRouter);
router.use(analysisRouter);
router.use(competitorsRouter);
router.use(contentRouter);
router.use(videosRouter);
router.use(renderRouter);
router.use(imagesRouter);
router.use(campaignsRouter);
router.use(adminRouter);
router.use(adminCreditsRouter);
router.use(adminCreditStatusRouter);
router.use(storageRouter);
router.use(googleAdsRouter);
router.use(metaAdsRouter);
router.use(authMetaRouter);
router.use(stripeRouter);
router.use(seoRouter);
router.use(seoToolsRouter);
router.use(teamRouter);
router.use(usageRouter);
router.use(scenesRouter);
router.use(assembleRouter);
router.use(narrationRouter);
router.use(renderAdminRouter);
router.use(videoWalletRouter);
router.use(adminVideoRouter);
router.use(analyzeWebsiteRouter);
router.use(ownerRouter);
router.use(supportRouter);
router.use(zTutorRouter);

export default router;
